.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ARM2HPDL 1 "November 19, 2005"
.SH NAME
arm2hpdl \- part of the printer driver foo2zjs
.SH SYNOPSIS
.B arm2hpdl [options] sihp1005.img > sihp1005.dl
.SH DESCRIPTION
.B arm2hpdl
adds HP download header/trailer to an ARM ELF binary.
If the file already has an HP header there is no need to use arm2hpdl.
.PP
.SH AUTHOR
arm2hpdl was written by Rick Richardson <rickr@mn.rr.com> .
.PP
This manual page was written by Steffen Joeris <steffen.joeris@skolelinux.de>,
for the Debian project (but may be used by others).
