#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_reset foo2zjs/list
db_input medium foo2zjs/list || true
db_go

#db_get foo2zjs/list

#case "$RET" in
#    "Hp Laserjet 1000")
#        PRINTER="1000"
#    ;;
#esac
