.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FOO2HP2600-wrapper 1 "November  19, 2005"
.SH NAME
foo2hp2600-wrapper \- part of the printer driver foo2zjs
.SH SYNOPSIS
.B foo2hp2600-wrapper [options] [ps-file]
.SH DESCRIPTION
.B foo2hp2600-wrapper
is a foomatic printer wrapper for the foo2hp2600 printer driver.
This script reads a Postscript ps-file or standard input
and converts it to Zenographics ZjStream printer format.
.PP
.SH Normal Options:
.TP
.B \-b bits
Bits per plane (1 or 2) [1]
.TP
.B \-c
Print in color (else monochrome)
.TP
.B \-d duplex
Duplex code to send to printer [1]
1=off, 2=longedge, 3=shortedge
.TP
.B \-m media          
Media code to send to printer [1]
1=standard, 2=transparency, 3=glossy, 257=envelope,
259=letterhead, 261=thickstock, 262=postcard, 263=labels
.TP
.B \-p paper          
Paper code [1]
1=letter, 5=legal, 7=executive, 9=A4, 11=A5, 13=B5
.TP
.B \-n copies         
Number of copies [1]
.TP
.B \-r <xres>x<yres>  
Set device resolution in pixels/inch [600x600]
.TP
.B \-s source         
Source code to send to printer [7]
1=upper, 2=lower, 4=manual, 7=auto
Code numbers may vary with printer model.
-2 / -4           2-up, 4-up

.SH Printer Tweaking Options:
.TP
.B \-u <xoff>x<yoff>  
Set offset of upper left printable in pixels [varies]
.TP
.B \-l <xoff>x<yoff>  
Set offset of lower right printable in pixels [varies]
.TP
.B \-L mask           
Send logical clipping values from -u/-l in ZjStream [3]
0=no, 1=Y, 2=X, 3=XY
.TP
.B \-P                
Do not output START_PLANE codes.  May be needed by some
monochrome-only printers.
.TP
.B \-X padlen         
Add extra zero padding to the end of BID segments [16]

.SH Color Tweaking Options:
.TP
.B \-g gsopts         
Additional options to pass to Ghostscript, such as
-dDITHERPPI=nnn, etc.  May appear more than once. []
.TP
.B \-G profile.icm    
Convert profile.icm to a Postscript CRD using icc2ps and
adjust colors using the setcolorrendering PS operator.
/usr/share/foo2zjs/icm/ will be searched for profile.icm.
.TP
.B \-I intent         
Select profile intent from ICM file [0]
0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute
.TP
.B \-G gamma-file.ps  
Prepend gamma-file to the Postscript input to perform
color correction using the setcolortransfer PS operator.

.SH Debugging Options:
.TP
.B \-S plane          
Output just a single color plane from a color print [all]
1=Cyan, 2=Magenta, 3=Yellow, 4=Black
.TP
.B \-D lvl            
Set Debug level [0]
.TP
.B \-V                $Id: foo2hp2600-wrapper.in,v 1.5 2005/11/13 14:57:13 rick Exp $

.SH AUTHOR
foo2hp2600-wrapper was written by Rick Richardson <rickr@mn.rr.com> .
.PP
This manual page was written by Steffen Joeris <steffen.joeris@skolelinux.de>,
for the Debian project (but may be used by others).
