.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FOO2ZJS-ICC2PS 1 "November  20, 2005"
.SH NAME
foo2zjs-icc2ps \- part of the printer driver foo2zjs
.SH SYNOPSIS
.B foo2zjs-icc2ps [flags] [output file]
.SH DESCRIPTION
.B foo2zjs-icc2ps
generates PostScript CRD or CSA from ICC profiles.
If no file is given, output goes to stdout.
You can specify by -i or -o the desired profile(s).
Devicelink profiles are accepted as long as input
for CRD / output for CSA were XYZ or Lab.
.PP
.SH Flags
.TP
.B \-i<profile>
Input profile: Generates Color Space Array (CSA)
.TP
.B \-o<profile>
Output profile: Generates Color Rendering Dictionary (CRD)
.TP
.B \-t<0,1,2,3>
Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute)
.SH AUTHOR
foo2zjs-icc2ps was written by Rick Richardson <rickr@mn.rr.com> .
.PP
This manual page was written by Steffen Joeris <steffen.joeris@skolelinux.de>,
for the Debian project (but may be used by others).
