.TH lavadecode 1 "Thu Jan 04 22:10:08 2007" "lavadecode 0.0"
.SH NAME
lavadecode \- Decode a XQX stream into human readable form.
.SH SYNOPSIS
.B lavadecode
.RI [ options "] <" zjs-file
.SH DESCRIPTION
.B lavadecode
decodes a LAVAFLOW stream into human readable form.
.P
A LAVAFLOW stream is the printer langauge used by some Konica Minolta
printers, such as the KM magicolor 2530 DL.

.SH COMMAND LINE OPTIONS
These are the options that can appear on the command line.
.TP
.BI \-d\0 basename
Basename of .pbm file for saving decompressed planes.
.TP
.BI \-h
Print hex file offsets.
.TP
.BI \-o
Print file offsets.
.TP
.BI \-D\0 level
Set Debug level [0].

.SH EXAMPLES
Decode an LAVAFLOW stream file created by foo2lava.

.nf
.ft CW
$ lavadecode -h < testpage.prn
     0: \\033%-12345X@PJL JOB NAME="stdin"
    1f: \\033%-12345X@PJL JOB USERNAME=""
    3d: \\033%-12345X@PJL JOB TIMESTAMP="12/12/2006"
    66: \\033%-12345X@PJL JOB OSINFO="Linux/2.6.17-1.2187_FC5"
    99: \\033%-12345X@PJL ENTER LANGUAGE=LAVAFLOW
    bf: \\033E                   RESET
    c1: \\033&l0S                DUPLEX
    c6: \\033&l0G
    cb: \\033&u1200D             X RESOLUTION
    d3: \\033&l1X                COPIES
    d8: \\033&x1X                TRANSMIT ONCE COPIES
    dd: \\033&l0O                ORIENTATION
    e2: \\033*r1U                NBIE
    e7: \\033*g8W                BW/COLOR
    ec: \\033*b1234M             COMPRESSION
    f4: \\033&l2A                PAGE SIZE
    f9: \\033&l255H              PAPER SOURCE
   100: \\033&l0M                MEDIA TYPE
   105: \\033&l0E                TOP MARGIN
   10a: \\033*r9820S             X RASTER
   112: \\033*r6410T             Y RASTER
   11a: \\033&l0U
   11f: \\033&l0Z
   124: \\033*p200X              X OFFSET
   12b: \\033*p200Y              Y OFFSET
   132: \\033*r1A                [Page 1]
   137: \\033*b20V               [black]
                DL = 0, D = 0, P = 1, - = 0, XY = 9820 x 6410
                L0 = 128, MX = 16, MY = 0
                Order   = 3  ILEAVE SMID
                Options = 92  LRLTWO TPDON TPBON DPON
                51 stripes, 0 layers, 1 planes

   151: \\033*b65536W    JBIG data (cont)
 1015a: \\033*b27374W    JBIG data (cont)
 16c51: \\033*r0C                END PAGE
 16c56: \\033E                   RESET
 16c58: \\033%-12345X
.ft P
.fi

.SH FILES
.BR /usr/bin/lavadecode
.SH SEE ALSO
.BR foo2lava-wrapper (1),
.BR foo2lava (1)
.SH "AUTHOR"
Rick Richardson <rick.richardson@comcast.net>
.br
http://foo2xqx.rkkda.com/
'/"
'/"
'/"
.em pdf_outline
