#!/bin/sh
set -e

. /usr/share/debconf/confmodule

UDEVDIR=/etc/udev/rules.d
RULESNAME=hplj10xx.rules
RULES=/etc/udev/rules.d/11-hplj10xx.rules
USBDIR=/etc/hotplug/usb


if [ "$1" = configure ]; then
    mkdir -p /var/cache/foo2zjs
    cd /var/cache/foo2zjs

    db_get foo2zjs/list

    HOTPLUG=0

    case "$RET" in
        "Hp Laserjet 1000")
            PRINTER="1000"
            HOTPLUG=1
            ;;
        "Hp Laserjet 1005")
            PRINTER="1005"
            HOTPLUG=1
            ;;
        "Hp Laserjet 1018")
            PRINTER="1018"
            HOTPLUG=1
            ;;
        "Hp Laserjet 1020")
            PRINTER="1020"
            HOTPLUG=1
            ;;
        "Samsung CLP-300")
            PRINTER="300"
            ;;
        "Samsung CLP-600")
            PRINTER="600"
            ;;
        "Samsung CLX-3160")
            PRINTER="3160"
            ;;
        "Xerox Phaser 6110")
            PRINTER="6110"
            ;;
    esac

    getweb $PRINTER
    
    if [ $HOTPLUG == 1 ]; then
        [ -d $USBDIR ] || install -d -m 755 $USBDIR
        install -c -m 755 /usr/sbin/hplj1000 $USBDIR
        ln -sf $USBDIR/hplj1000 $USBDIR/hplj1005
        ln -sf $USBDIR/hplj1000 $USBDIR/hplj1018
        ln -sf $USBDIR/hplj1000 $USBDIR/hplj1020
        $USBDIR/hplj1000 install-usermap
        $USBDIR/hplj1005 install-usermap
        $USBDIR/hplj1018 install-usermap
        $USBDIR/hplj1020 install-usermap
    fi
fi
