.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH USB_PRINTERID 1 "November  20, 2005"
.SH NAME
usb_printerid \- part of the printer driver foo2zjs
.SH SYNOPSIS
.B usb_printerid device
.SH DESCRIPTION
.B usb_printerid
lists the ID of a printer device.
.PP
.SH AUTHOR
usb_printerid was written by Rick Richardson <rickr@mn.rr.com> .
.PP
This manual page was written by Steffen Joeris <steffen.joeris@skolelinux.de>,
for the Debian project (but may be used by others).
