######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 27 01:13:29 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h
SOURCES += gui.cpp main.cpp
